# Generated by Django 3.0.1 on 2019-12-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='final_def_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='final_def_title',
            field=models.CharField(default='Soon', max_length=255),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='first_def_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='first_def_title',
            field=models.CharField(default='Soon', max_length=255),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='mid_def_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='mid_def_title',
            field=models.CharField(default='Soon', max_length=255),
        ),
    ]
