# Generated by Django 3.0.1 on 2019-12-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191220_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='final_def_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='first_def_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='mid_def_time',
            field=models.DateField(null=True),
        ),
    ]
