# Generated by Django 3.0.1 on 2019-12-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191220_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='teacher',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
